url: https://studentgig.github.io
baseurl: 

# Site settings
title: StudentGig.net
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 00C4C4
  secondary: 03D6D6  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Arun Das
  pic: 1
  position: Web Developement
  social:
    - title: twitter
      url: #
    - title: facebook
      url: https://www.facebook.com/arundas1409?fref=ts
    - title: linkedin
      url: #

- name: Xiao Huang
  pic: 2
  position: iOS Developeent
  social:
    - title: twitter
      url: #
    - title: facebook
      url: https://www.facebook.com/HenryXiaoHuang
    - title: linkedin
      url: #

- name: Taylor Meeks
  pic: 3
  position: Startup Specialist
  social:
    - title: twitter
      url: #
    - title: facebook
      url: https://www.facebook.com/taylor.meeks.16
    - title: linkedin #google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: #
  - title: facebook
    url: https://www.facebook.com/studentgigmarketplace
  - title: stack-overflow
    url: #
  - title: bitbucket 
    url: #
  - title: github
    url: #

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty